webtalk_init -webtalk_dir C:\\Users\\lukas\\Documents\\SoC_Lab\\FPGA_MNIST\\vivado\\Software\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-12-11 19:10:48" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211128814_1777529682_210668560_605" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ehfidopu8vaam8156gdjpscke4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.364 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1576078196077" -context "sdk\\\\application/1576078196077"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1576078196077"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1576078196077"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1576078196077"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1576078196077"
webtalk_add_data -client sdk -key Procused -value "" -context "sdk\\\\application/1576078196077"
webtalk_add_data -client sdk -key projSize -value "123.171875" -context "sdk\\\\application/1576078196077"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1576087848221"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1576087848221"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1576087848221"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1576087848221"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1576087848221"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1576087848221"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1576087848221"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1576087848221"
webtalk_transmit -clientid 4175012331 -regid "211128814_1777529682_210668560_605" -xml C:\\Users\\lukas\\Documents\\SoC_Lab\\FPGA_MNIST\\vivado\\Software\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\lukas\\Documents\\SoC_Lab\\FPGA_MNIST\\vivado\\Software\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\lukas\\Documents\\SoC_Lab\\FPGA_MNIST\\vivado\\Software\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
