# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_xbar_0/zedboard_xbar_0.xci
# IP: The module: 'zedboard_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_xbar_0/zedboard_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_xbar_0/zedboard_xbar_0.xci
# IP: The module: 'zedboard_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_xbar_0/zedboard_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
