# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zedboard/zedboard.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard || ORIG_REF_NAME==zedboard} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_processing_system7_0_0/zedboard_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_processing_system7_0_0 || ORIG_REF_NAME==zedboard_processing_system7_0_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_axi_dma_0_0/zedboard_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_axi_dma_0_0 || ORIG_REF_NAME==zedboard_axi_dma_0_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_ps7_0_axi_periph_0/zedboard_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_ps7_0_axi_periph_0 || ORIG_REF_NAME==zedboard_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_rst_ps7_0_100M_0/zedboard_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_rst_ps7_0_100M_0 || ORIG_REF_NAME==zedboard_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_axi_smc_0/zedboard_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_axi_smc_0 || ORIG_REF_NAME==zedboard_axi_smc_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_nn_mem_controller_0_0/zedboard_nn_mem_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_nn_mem_controller_0_0 || ORIG_REF_NAME==zedboard_nn_mem_controller_0_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_blk_mem_gen_0_0/zedboard_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_blk_mem_gen_0_0 || ORIG_REF_NAME==zedboard_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_xlconcat_0_0/zedboard_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_xlconcat_0_0 || ORIG_REF_NAME==zedboard_xlconcat_0_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_xbar_0/zedboard_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_xbar_0 || ORIG_REF_NAME==zedboard_xbar_0} -quiet] -quiet

# IP: bd/zedboard/ip/zedboard_auto_pc_0/zedboard_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_auto_pc_0 || ORIG_REF_NAME==zedboard_auto_pc_0} -quiet] -quiet

# XDC: bd/zedboard/zedboard_ooc.xdc
