# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.cache/wt [current_project]
set_property parent.project_path C:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/NN_IP [current_project]
set_property ip_output_repo c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/hdl/zedboard_wrapper.vhd
add_files C:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/zedboard.bd
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_processing_system7_0_0/zedboard_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_dma_0_0/zedboard_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_dma_0_0/zedboard_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_dma_0_0/zedboard_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_rst_ps7_0_100M_0/zedboard_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_rst_ps7_0_100M_0/zedboard_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_rst_ps7_0_100M_0/zedboard_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_10/bd_1ec0_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_16/bd_1ec0_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_20/bd_1ec0_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_21/bd_1ec0_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_22/bd_1ec0_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_23/bd_1ec0_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_24/bd_1ec0_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_25/bd_1ec0_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_17/bd_1ec0_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_18/bd_1ec0_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_19/bd_1ec0_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_11/bd_1ec0_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_12/bd_1ec0_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_2/bd_1ec0_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_3/bd_1ec0_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_4/bd_1ec0_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_5/bd_1ec0_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_6/bd_1ec0_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_1/bd_1ec0_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/bd_0/ip/ip_1/bd_1ec0_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_blk_mem_gen_0_0/zedboard_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_xbar_0/zedboard_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/ip/zedboard_auto_pc_0/zedboard_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/lukas/Documents/SoC_Lab/FPGA_MNIST/vivado/FPGA-MNIST/FPGA-MNIST.srcs/sources_1/bd/zedboard/zedboard_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zedboard_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zedboard_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zedboard_wrapper_utilization_synth.rpt -pb zedboard_wrapper_utilization_synth.pb"
