# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from __future__ import absolute_import, print



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _EggNetDriverCore
else:
    import _EggNetDriverCore

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


DATA_WIDTH = _EggNetDriverCore.DATA_WIDTH
OUTPUT_NUMBER = _EggNetDriverCore.OUTPUT_NUMBER

def init_network(ip_name, net):
    return _EggNetDriverCore.init_network(ip_name, net)

def close_network():
    return _EggNetDriverCore.close_network()

def forward(image_buffer):
    return _EggNetDriverCore.forward(image_buffer)

def print_err(code):
    return _EggNetDriverCore.print_err(code)

def get_network_structure(net_ptr):
    return _EggNetDriverCore.get_network_structure(net_ptr)

def print_network():
    return _EggNetDriverCore.print_network()

def activate_debug_mode():
    return _EggNetDriverCore.activate_debug_mode()

def read_pixel(pixel, layer, row, col, channel):
    return _EggNetDriverCore.read_pixel(pixel, layer, row, col, channel)

def read_row(pixel, layer, row, channel):
    return _EggNetDriverCore.read_row(pixel, layer, row, channel)

def read_channel(pixel, layer, channel):
    return _EggNetDriverCore.read_channel(pixel, layer, channel)

def read_layer(pixel, layer):
    return _EggNetDriverCore.read_layer(pixel, layer)


